default:
  dora_dir: /scratch4/users/od/repos/audiocraft/logs/
  partitions:
    global: debug
    team: debug
  reference_dir: /scratch4/users/od/repos/audiocraft/logs/
darwin:  # if we detect we are on a Mac, then most likely we are doing unit testing etc.
  dora_dir: /tmp/audiocraft_${oc.env:USER}
  partitions:
    global: debug
    team: debug
  reference_dir: /tmp
