# @package __global__

# total samples obtained from MusicCaps = 5469
# (out of 5521 due to AudioSet corrupted samples)
datasource:
  max_sample_rate: 44100
  max_channels: 2

  train: egs/musiccaps/train  
  valid: egs/musiccaps/valid  
  evaluate: egs/musiccaps/test
  generate: egs/musiccaps/test # identical to evaluate
